Add the singular user command, analogous to the single tweet command
DocNow/twarc pull request #599
Opened 2022-02-22 06:42 UTC by SamHames

This adds the user command, which takes a single user id. This is a direct analogue of the single tweet command, so we know have tweet/tweets and user/users.

Closes #598

2022-02-22 13:13 UTC, edsu commented
It looks like id works but username does not?

```
$ twarc2 user jack
⚡ The `ids` query parameter value [jack] is not valid
```

2022-02-22 13:29 UTC, SamHames commented
The design mirrors the users command, so there's a  --username flag to
handle that case explicitly.

Not sure that's necessarily the best approach for the long term, but it's
at least consistent with its sibling command.

Given how common that specific use case is do you think it's worth
considering another approach?



On Tue, 22 Feb 2022, 23:13 Ed Summers, ***@***.***> wrote:

> It looks like id works but username does not?
>
> $ twarc2 user jack
>
> ⚡ The `ids` query parameter value [jack] is not valid
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DocNow/twarc/pull/599#issuecomment-1047784097>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACADAUKOKIR3HXZCI3N4ISLU4ODZJANCNFSM5PAOK3PQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-22 13:31 UTC, edsu requested changes
I noticed that looking up by username doesn't work?

```
$ twarc2 user jack
⚡ The `ids` query parameter value [jack] is not valid
```

Maybe that should be fixed or it shouldn't advertise that it can lookup by username?

2022-03-04 03:27 UTC, igorbrigadir commented
yes, would be nice to have `twarc2 user jack` work - - very useful for arbitrarily pulling out a user ID on the go!

2022-03-04 05:02 UTC, SamHames commented
I added the name/id disambiguation as part of the command to make it clear, as well as updating the docstrings to better align with that.

    Get the profile data for a single user by either username or ID.

    To look up a user by ID:

        twarc2 user id 12

    To look up a user by username:

        twarc2 user name jack

2022-03-11 16:14 UTC, igorbrigadir approved these changes

2022-03-11 16:16 UTC, igorbrigadir commented
I really like this `"name-or-id"` approach, and the command examples in the docs!

2022-03-11 16:35 UTC, edsu approved these changes

2022-03-11 16:38 UTC, edsu commented
I like it too! It could be useful for some other commands like`timeline`.

2022-03-12 20:55 UTC, igorbrigadir commented
I think this is good to go!

2022-03-12 20:55 UTC, merged